### ISSUE TITLE
Deploying from tags currently incompatible with use of environments

### ISSUE THREAD

**Issue by jdeschamps** [pydev-guide/pyrepo-copier#14]
A recent Github security update has [broken the current deployment pipeline](https://github.com/orgs/community/discussions/62991), whereby a CI runs on tags in an environment and deploys to PyPi using the trusted publishers.

https://github.com/pydev-guide/pyrepo-copier/pulls removes the `release` environment. 

We could leave this issue open to revisit it later, or close it if environments are not that useful for the type of applications this repo caters to!

**Comment by jdeschamps** [comment]
In the light of the discussion in https://github.com/pydev-guide/pyrepo-copier/pull/13, this issue is not necessary!

**Comment by tlambert03** [comment]
looks like the original issue is now fixed at github: 
https://github.blog/changelog/2023-10-06-actions-secure-deployment-rollouts-to-protected-environments-based-on-select-tag-patterns/

I'm happy enough with the current pattern... but just FYI
