### ISSUE TITLE
Tag update upon PR merging

### ISSUE THREAD

**Issue by jdeschamps** [pydev-guide/pyrepo-copier#17]
If I am not mistaken, `copier` uses the latest known tag of the template as a reference. So it would make sense to automatically update the tag after each new PR.

Not sure how to technically do that through an action though!

**Comment by tlambert03** [comment]
oh very good point! 
for what it's worth, we could change the instructions to:
```
copier copy --vcs-ref HEAD gh:pydev-guide/pyrepo-copier your-package-name
```

but I find that pretty ugly, and after a little searching I wasn't able to come up with a better syntax (using `@HEAD` for example).

I guess we'll need to tag everything :/

**Comment by tlambert03** [comment]
ok, I think it should be working now, retagging everything pushed to main as v1

https://github.com/pydev-guide/pyrepo-copier/blob/main/.github/workflows/autotag.yml

**Comment by jdeschamps** [comment]
Ahah damn it, I was trying out as well! Awesome. :D

**Comment by tlambert03** [comment]
oh shoot, sorry to waste your time!

**Comment by jdeschamps** [comment]
Not at all! 😄
