### ISSUE TITLE
Copier command should include sub-command `copy` for copier 8.0.0

### ISSUE THREAD

**Issue by jluethi** [pydev-guide/pyrepo-copier#4]
Hey @tlambert03 

Super cool new Python repository template! I was just starting a new python package and decided to try this over the cookie cutter templates.

One thing I noticed with copier 8.0.0 (the default that gets installed with `pip install copier`) is that the command:

```
copier gh:pydev-guide/pyrepo-copier your-package-name
```

doesn't seem to work anymore and I get a `Unknown sub-command 'gh:pydev-guide/pyrepo-copier'`.

Instead, this command now works:

```
copier copy gh:pydev-guide/pyrepo-copier your-package-name
```

Edit: Just to confirm: In copier 7.2.0, that still used to work, so must have been a change in the recent 8.0.0 update

**Comment by tlambert03** [comment]
thanks!
