### ISSUE TITLE
Broken with copier v8

### ISSUE THREAD

**Issue by tlambert03** [pydev-guide/pyrepo-copier#8]
copier v8 with https://github.com/copier-org/copier/pull/1126 broke most of the functionality here.

After reading through some issues, I'm still not sure how to fix it, and it's possible the copier team sees it as a "won't-fix" issue.  
See https://github.com/orgs/copier-org/discussions/1204 where I've opened a question

**Comment by jdeschamps** [comment]
Let's see...

**Comment by tlambert03** [comment]
This repo works again after https://github.com/copier-org/copier/pull/1220 ... will close this issue when a new release includes that PR

**Comment by jdeschamps** [comment]
Seems like it has been released: https://github.com/copier-org/copier/releases/tag/v8.1.0 🎉
